# Service for Loki
apiVersion: v1
kind: Service
metadata:
  name: loki # Service name used by Grafana Alloy and Grafana
  namespace: observabilidad
spec:
  selector:
    app: loki
  ports:
    - name: http-metrics
      protocol: TCP
      port: 3100
      targetPort: 3100
    - name: grpc
      protocol: TCP
      port: 9095
      targetPort: 9095
  type: LoadBalancer
---
# Service for Prometheus
apiVersion: v1
kind: Service
metadata:
  name: prometheus # Service name used by Grafana
  namespace: observabilidad
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: observabilidad
spec:
  selector:
    app: tempo
  ports:
    - name: http
      port: 4318
      targetPort: 4318
    - name: grpc
      port: 4317
      targetPort: 4317
  type: LoadBalancer
---
# Service for Grafana
apiVersion: v1
kind: Service
metadata:
  name: grafana # Service name used by users to access UI
  namespace: observabilidad
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000 # Port exposed by the Service
      targetPort: 3000 # Port Grafana listens on
  type: LoadBalancer # Change to LoadBalancer or NodePort to access Grafana from outside the cluster
  # nodePort: 30000 # Uncomment and set if using NodePort (range 30000-32767)