// <auto-generated/>
global using Axity.Commons.Filters;
global using Axity.Kafka;
global using Toks.Loyalty.test.Facade;
global using Toks.Loyalty.test.Api;
global using Toks.Loyalty.test.Persistence;
global using Toks.Loyalty.test.Services;
global using Microsoft.AspNetCore.Mvc;
global using Serilog;
global using Serilog.Events;
global using StackExchange.Redis;
global using Steeltoe.Extensions.Configuration.Placeholder;