// <auto-generated/>
global using AutoMapper;
global using Axity.Commons.Exceptions;
global using Axity.Commons.Extensions;
global using Toks.Loyalty.test.Services.Mapping;
global using Microsoft.Extensions.DependencyInjection;