// <auto-generated/>
global using Toks.Loyalty.test.Model.Entities;
global using Toks.Loyalty.test.Persistence.Context;
global using Toks.Loyalty.test.Persistence.DAO.Tests;
global using Toks.Loyalty.test.Persistence.DAO.Tests.Impl;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;
