version: "3.9"

services:
  api:
    #image: repo/Bill-api
    container_name: bill-api
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      poetry run uvicorn app.infrastructure.api.main:app --reload --workers 3 --host 0.0.0.0 --port 3003
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "3003:3003"
