apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-alloy
  namespace: observabilidad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-alloy
  template:
    metadata:
      labels:
        app: grafana-alloy
    spec:
      containers:
        - name: grafana-alloy
          image: grafana/agent:latest
          args:
            - -config.file=/etc/agent/alloy-config.yaml
          volumeMounts:
            - name: alloy-config
              mountPath: /etc/agent
            - name: varlog
              mountPath: /var/log/containers
              readOnly: true
      volumes:
        - name: alloy-config
          configMap:
            name: alloy-config
        - name: varlog
          hostPath:
            path: /var/log/containers
            type: DirectoryOrCreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: observabilidad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.0.0
          args:
            - -config.file=/etc/loki/local-config.yaml
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: loki-storage
              mountPath: /var/loki
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: loki-storage
          persistentVolumeClaim:
            claimName: loki-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: observabilidad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.51.2
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --enable-feature=exemplar-storage
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: observabilidad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.4.1
          args:
            - '--target=all'
            - '--storage.trace.backend=local'
            - '--storage.trace.local.path=/var/tempo'
            - '--auth.enabled=false'
          ports:
            - containerPort: 4317
            - containerPort: 4318
          volumeMounts:
            - name: tempo-storage
              mountPath: /var/tempo
      volumes:
        - name: tempo-storage
          persistentVolumeClaim:
            claimName: tempo-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: observabilidad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.4.2
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboard-definitions
              mountPath: /etc/grafana/dashboards
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
            items:
              - key: datasources.yaml
                path: datasources.yaml
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards
            items:
              - key: dashboards.yaml
                path: dashboards.yaml
        - name: grafana-dashboard-definitions
          configMap:
            name: grafana-dashboard-definitions