apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-alloy
  namespace: observabilidad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-alloy
  template:
    metadata:
      labels:
        app: grafana-alloy
    spec:
      volumes:
        - name: alloy-config-volume
          configMap:
            name: grafana-alloy-config
        - name: shared-logs-volume
          persistentVolumeClaim:
            claimName: alloy-shared-logs-pvc
      containers:
        - name: grafana-alloy
          image: grafana/agent:latest
          command: ["-config.file=/etc/agent/agent.yaml"]
          volumeMounts:
            - name: alloy-config-volume
              mountPath: /etc/agent/agent.yaml
              subPath: alloy-config.yaml
            - name: shared-logs-volume
              mountPath: /var/log/containers
          dependsOn:
            - loki