apiVersion: v1
kind: PersistentVolume
metadata:
  name: observability-pv
  namespace: observabilidad
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/observability