apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: observabilidad
spec:
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: observabilidad
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  # Si quieres acceder a Prometheus desde fuera del clúster para desarrollo:
  # type: NodePort
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: observabilidad
spec:
  selector:
    app: tempo
  ports:
    - protocol: TCP
      name: otlp-grpc
      port: 4317
      targetPort: 4317
    - protocol: TCP
      name: otlp-http
      port: 4318
      targetPort: 4318
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: observabilidad
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  # Para acceder a Grafana desde tu navegador:
  type: LoadBalancer # Recomendado para acceso externo estable
  # type: NodePort    # Alternativa si no tienes LoadBalancer