apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: tt
spec:
  selector:
    app: transaction-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
