apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: monitoring
  labels:
    app: transaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
      - name: transaction-api
        image: transaction-service-api:1.0.0
        envFrom:
          - configMapRef:
              name: trx-service-env
        ports:
          - containerPort: 3001
        command:
        - sh
        - -c
        - >
          uvicorn app.infrastructure.api.main:app --host 0.0.0.0 --port 3001 2>&1 | tee /var/log/containers/trx-service.log
        volumeMounts:
        - name: shared-logs-volume
          mountPath: /var/log/containers
      volumes:
      - name: shared-logs-volume
        persistentVolumeClaim:
          claimName: shared-logs-pvc
